version: "3"
services:
  docker-registry:
      restart: always
      image: registry
      ports:
          - 5000:5000
      environment:
          REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
          REGISTRY_HTTP_TLS_KEY: /certs/domain.key
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      volumes:
          - /data/webserver/docker-registry/data:/var/lib/registry
          - /data/webserver/docker-registry/conf/certs:/certs
          - /data/webserver/docker-registry/conf/auth:/auth
