version: "3"
services:
  registry:
      restart: always
      image: registry
      ports:
          - 5000:5000
      environment:
          - REGISTRY_LOG_LEVEL=info
          - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
          - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.crt
          - REGISTRY_HTTP_TLS_KEY=/certs/registry.key
          - REGISTRY_AUTH=token
          - REGISTRY_AUTH_TOKEN_REALM=https://gitlab.17173.com/jwt/auth
          - REGISTRY_AUTH_TOKEN_SERVICE=container_registry
          - REGISTRY_AUTH_TOKEN_ISSUER=gitlab-issuer
          - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/registry.crt
          - REGISTRY_STORAGE_DELETE_ENABLED=true
      volumes:
          - /data/webserver/docker-registry/data:/var/lib/registry
          - /data/webserver/docker-registry/conf/certs:/certs
          - /data/webserver/docker-registry/conf/auth:/auth
          #- /data/webserver/docker-registry/conf/config.yml:/etc/docker/registry/config.yml
