version: 0.1
storage:
  filesystem:
    rootdirectory: /var/lib/registry
auth:
  token:
    realm: https://192.168.50.128:8000/jwt/auth
    service: container_registry
    issuer: gitlab-issuer
    rootcertbundle: /certs/domain.crt
  htpasswd:
    realm: basic-realm
    path: /auth/htpasswd
