version: 0.1
log:
  level: info
storage:
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 1000
  delete:
    enabled: true
auth:
  token:
    realm: http://192.168.50.128:8000/jwt/auth
    service: container_registry
    issuer: gitlab-issuer
    rootcertbundle: /certs/registry.crt
http:
  tls:
    certificate: /certs/registry.crt
    key: /certs/registry.key
