concurrent = 10
check_interval = 0

[[runners]]
  name = "docker-runner"
  url = "http://192.168.50.128:8000"
  token = "e3f1720c20ed8e4fb9a4c587b34026"
  executor = "docker"
  clone_url = "http://192.168.50.128:8000"
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = true
    disable_cache = false
    volumes = ["/cache"]
    pull_policy = "if-not-present"
    shm_size = 0
  [runners.cache]

[[runners]]
  name = "docker-runner"
  url = "http://192.168.50.128:8000"
  token = "79b55133b23a762ae494d3be97cf5a"
  executor = "docker"
  clone_url = "http://192.168.50.128:8000"
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = true
    disable_cache = false
    volumes = ["/cache"]
    pull_policy = "if-not-present"
    shm_size = 0
  [runners.cache]

[[runners]]
  name = "docker-runner"
  url = "http://192.168.50.128:8000"
  token = "2a6288ff0e62af9fc465b7363ef05a"
  executor = "docker"
  clone_url = "http://192.168.50.128:8000"
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = true
    disable_cache = false
    volumes = ["/cache","/var/run/docker.sock:/var/run/docker.sock","/etc/docker/daemon.json:/etc/docker/daemon.json"]
    shm_size = 0
    pull_policy = "if-not-present"
  [runners.cache]
