version: "3"

services:
    chrome:
      image: ainow/chrome
      restart: always
      ports:
       - "9222:9222"
       - "9515:9515"
      shm_size: 2048M
      ulimits:
        nproc: 65535
        nofile:
          soft: 65535
          hard: 65535
      command:
        ["--verbose","--whitelisted-ips"]

    python:
      image: python:alpine
      volumes:
       - /data:/data
      restart: always
      shm_size: 2048M
      networks:
       - default
       - mysql_default
       - redis_default
      external_links:
        - mysql:mysql_server
        - redis_redis_1:redis_server   
      ulimits:
        nproc: 65535
        nofile:
          soft: 65535
          hard: 65535
      command:
        ["init"]
          
networks:
  mysql_default:
    external: true
  redis_default:
    external: true
