version: "3"
services:
    mysql:
      image: mysql:5.7.22
      volumes:
       - /data/webserver/mysql/data:/var/lib/mysql
       - /data/webserver/mysql/conf:/etc/mysql/conf.d
       
      environment:
       - MYSQL_ROOT_PASSWORD=123456
      
      restart: always
      ports:
       - "3306:3306"
      shm_size: 2048M
      ulimits:
        nproc: 65535
        nofile:
          soft: 65535
          hard: 65535